-- ── item 表新增字段 ──────────────────────────
ALTER TABLE item ADD COLUMN IF NOT EXISTS image_urls TEXT;
ALTER TABLE item ADD COLUMN IF NOT EXISTS category VARCHAR(32) DEFAULT '';
ALTER TABLE item ADD COLUMN IF NOT EXISTS condition_level VARCHAR(16) DEFAULT '';
ALTER TABLE item ADD COLUMN IF NOT EXISTS campus VARCHAR(64) DEFAULT '';
ALTER TABLE item ADD COLUMN IF NOT EXISTS created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE item ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ── orders 表新增字段 ──────────────────────────
ALTER TABLE orders ADD COLUMN IF NOT EXISTS created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS item_price INT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS buyer_name VARCHAR(64) DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS seller_name VARCHAR(64) DEFAULT '';
